"""Curriculum map: every book & bot from the reading list → the lesson it teaches → where it lives in this app."""

BOOKS = [
    # (title, author, group, lesson_en, lesson_fa, where_in_app)
    ("Technical Analysis of the Financial Markets", "John J. Murphy", "TA",
     "Trend is primary; confirm across price, momentum and volume; support/resistance, MA rules, oscillators' failure in trends.",
     "روند اصل است؛ تأیید هم‌زمان قیمت، مومنتوم و حجم؛ حمایت/مقاومت، قواعد میانگین متحرک، شکست اسیلاتورها در روند.",
     "strategy murphy_confirm · Chart overlays · Indicator Encyclopedia"),
    ("Japanese Candlestick Charting Techniques", "Steve Nison", "TA",
     "26 reversal/continuation candles; a candle only matters after a trend and at support/resistance.",
     "۲۶ الگوی کندلی برگشتی/ادامه؛ کندل فقط بعد از روند و روی حمایت/مقاومت معنا دارد.",
     "core/patterns.candlesticks · strategy nison_candles · Quant Lab ▸ Patterns"),
    ("Encyclopedia of Chart Patterns", "Thomas N. Bulkowski", "TA",
     "Objective identification rules + measured statistics (failure rate, average move, rank) for 39 patterns; the measure rule.",
     "قواعد عینی شناسایی + آمار اندازه‌گیری‌شده (نرخ شکست، میانگین حرکت، رتبه) برای ۳۹ الگو؛ قانون اندازه‌گیری.",
     "core/patterns.chart_patterns · strategy bulkowski_patterns · Quant Lab ▸ Patterns"),
    ("Trading for a Living / The New Trading for a Living", "Dr. Alexander Elder", "TA",
     "Triple Screen, Impulse System, Force Index, 2% and 6% rules, mind–method–money.",
     "سه‌صفحه، سیستم ایمپالس، Force Index، قانون ۲٪ و ۶٪، ذهن–روش–پول.",
     "strategies elder_triple_screen · elder_impulse · elder_force2 · Risk page gates"),
    ("Come Into My Trading Room", "Dr. Alexander Elder", "TA",
     "SafeZone stops, 2-day Force Index entries, the trader's journal & equity-curve discipline.",
     "استاپ SafeZone، ورود با Force Index دوروزه، ژورنال و انضباط منحنی سرمایه.",
     "strategies elder_force2 · elder_impulse_safezone (real SafeZone stop) · quant2.elder_money_rules (6% rule) · Journal"),
    ("How to Make Money in Stocks", "William J. O'Neil", "TA",
     "CAN SLIM; buy leaders breaking out of bases on volume; sell at −7/8% no matter what.",
     "CAN SLIM؛ خرید لیدرها هنگام شکست پایه با حجم؛ فروش در −۷/۸٪ بدون استثنا.",
     "strategies oneil_cup_handle · oneil_canslim · oneil_sell_rules (7-8% / 20-25% / 50-DMA exits) · minervini_tt"),
    ("Charting and Technical Analysis", "Fred McAllen", "TA",
     "Practical S/R, trend lines, volume confirmation, keep it simple.",
     "حمایت/مقاومت عملی، خطوط روند، تأیید حجم، ساده نگه دار.",
     "strategies sr_breakout_retest · market_structure · Chart"),
    ("Risk Management in Trading", "Steve Day", "RISK",
     "Hard limits: per-trade, total open, daily loss, drawdown-based size reduction.",
     "محدودیت‌های سخت: هر معامله، ریسک باز کل، ضرر روزانه، کاهش اندازه بر اساس افت سرمایه.",
     "core/psychology.gate · Advisor allocator · Risk page"),
    ("The Psychology of Trading", "Brett N. Steenbarger", "PSY",
     "Trade your state, not the market; journaling patterns; performance coaching metrics.",
     "وضعیت خودت را معامله کن نه بازار؛ الگوهای ژورنال؛ سنجه‌های مربی‌گری عملکرد.",
     "Quant Lab ▸ Psychology (checklist + audit) · Journal emotion field"),
    ("Trading in the Zone", "Mark Douglas", "PSY",
     "5 fundamental truths; think in probabilities; edge = series of trades, not one trade.",
     "۵ حقیقت بنیادی؛ احتمالاتی فکر کن؛ لبه = مجموعهٔ معاملات نه یک معامله.",
     "Pre-trade checklist · Grade/CI display everywhere"),
    ("The Disciplined Trader", "Mark Douglas", "PSY",
     "Rules exist to protect you from yourself; pre-define risk; accept losses mechanically.",
     "قوانین برای محافظت از تو در برابر خودت هستند؛ ریسک را از قبل تعریف کن؛ ضرر را مکانیکی بپذیر.",
     "Hard gates · stop-violation audit"),
    ("Thinking, Fast and Slow", "Daniel Kahneman", "PSY",
     "System 1 vs 2, loss aversion, disposition effect, overconfidence, narrow framing.",
     "سیستم ۱ و ۲، زیان‌گریزی، اثر تمایل، اعتمادبه‌نفس کاذب، قاب‌بندی تنگ.",
     "Journal audit: disposition, martingale, revenge detectors"),
    ("Fooled by Randomness", "Nassim N. Taleb", "PSY",
     "Track records are mostly noise; survivorship; you cannot tell skill from luck without enough n.",
     "سوابق عمدتاً نویزند؛ سوگیری بازمانده؛ بدون n کافی نمی‌توان مهارت را از شانس تشخیص داد.",
     "t-stat 'luck' check · need_n · Deflated Sharpe"),
    ("The Black Swan", "Nassim N. Taleb", "PSY",
     "Fat tails dominate; size for the unseen; never risk ruin for a small edge.",
     "دنباله‌های چاق حاکم‌اند؛ برای نادیده اندازه بگیر؛ هرگز برای لبهٔ کوچک ریسک ورشکستگی نکن.",
     "Tail-event audit · Monte-Carlo DD95 · risk-of-ruin"),
    ("Against the Gods", "Peter L. Bernstein", "RISK",
     "History of probability & risk; expected value; regression to the mean; diversification.",
     "تاریخ احتمال و ریسک؛ ارزش انتظاری؛ بازگشت به میانگین؛ تنوع‌بخشی.",
     "risk_of_ruin MC · correlation-aware allocator"),
    ("Algorithmic Trading and DMA", "Barry Johnson", "QUANT",
     "Market microstructure, order types, execution cost, slippage models.",
     "ریزساختار بازار، انواع سفارش، هزینهٔ اجرا، مدل‌های اسلیپیج.",
     "core/costs.py (spread + ATR-slippage) · next-open fills"),
    ("Algorithmic Trading: Winning Strategies", "Ernie Chan", "QUANT",
     "Stationarity (ADF), Hurst, half-life, cointegration & pairs, Bollinger-z, Kelly, regime.",
     "ایستایی (ADF)، هرست، نیمه‌عمر، هم‌انباشتگی و جفت‌ها، z بولینگر، کِلی، رژیم.",
     "core/quant.py · quant2.kalman_hedge · strategies chan_statarb · chan_kalman · Quant Lab ▸ Series & Pairs"),
    ("Quantitative Trading", "Ernie Chan", "QUANT",
     "Backtesting pitfalls (look-ahead, survivorship, data-snooping), Sharpe, Kelly sizing.",
     "دام‌های بک‌تست (نگاه به آینده، بازمانده، داده‌کاوی)، شارپ، اندازهٔ کِلی.",
     "next_open=True · OOS folds · quarter-Kelly cap"),
    ("Machine Trading", "Ernie Chan", "QUANT",
     "Factor models, time-series momentum, ML with strict CV, options of automation.",
     "مدل‌های فاکتور، مومنتوم سری زمانی، ML با CV سخت‌گیرانه.",
     "ML Lab (purged walk-forward) · regime_ensemble"),
    ("Advances in Financial Machine Learning", "Marcos López de Prado", "QUANT",
     "Triple-barrier labels, meta-labelling, fractional differentiation, CUSUM, purged CV, bet sizing, Deflated Sharpe, PBO.",
     "برچسب سه‌مانعی، متا‌لیبلینگ، تفاضل کسری، CUSUM، CV پاک‌شده، اندازهٔ شرط، شارپ تعدیل‌شده، PBO.",
     "core/ml.py (triple barrier, meta-label, purged WF) · core/quant.py (FFD, CUSUM, DSR, PBO, bet_size) · quant2 (sample weights, sequential bootstrap)"),
    ("Building Winning Algorithmic Trading Systems", "Kevin J. Davey", "QUANT",
     "Walk-forward testing, Monte-Carlo, incubation period before live, WFE ≥ 50%.",
     "واک‌فوروارد، مونت‌کارلو، دورهٔ انکوباسیون قبل از زنده، WFE ≥ ۵۰٪.",
     "Quant Lab ▸ Overfitting (WFE, incubation, Monkey test, MC trade resampling) · strategy davey_robust · Forward Test = incubation"),
    ("Automated Trading with R", "Chris Conlan", "QUANT",
     "Pipeline: data → indicators → rules → optimisation → execution; vectorised backtests.",
     "خط لوله: داده → اندیکاتور → قانون → بهینه‌سازی → اجرا؛ بک‌تست برداری.",
     "core architecture (data/indicators/strategies/backtest)"),
    ("Trading Systems: A New Approach", "Urban Järemo", "QUANT",
     "System development discipline; robustness over optimisation; simple rules.",
     "انضباط توسعهٔ سیستم؛ استواری به‌جای بهینه‌سازی؛ قواعد ساده.",
     "Validation Lab robustness score · parameter-perturbation PBO"),
    ("Python for Finance", "Yves Hilpisch", "PY",
     "pandas/numpy financial time series, vectorised strategies, performance.",
     "سری زمانی مالی با pandas/numpy، استراتژی برداری، کارایی.",
     "whole codebase (vectorised indicators/strategies)"),
    ("Mastering Python for Finance", "James Ma Weiming", "PY",
     "Statistical models, cointegration examples, event-driven backtester design.",
     "مدل‌های آماری، مثال‌های هم‌انباشتگی، طراحی بک‌تستر رویدادمحور.",
     "core/backtest.py (event-driven) · core/quant.cointegration"),
    ("Derivatives Analytics with Python", "Yves Hilpisch", "PY",
     "Volatility, Monte-Carlo simulation, risk-neutral valuation.",
     "نوسان، شبیه‌سازی مونت‌کارلو، ارزش‌گذاری ریسک‌خنثی.",
     "Monte-Carlo drawdown & ruin simulations"),
    ("Financial Theory with Python", "Yves Hilpisch", "PY",
     "Expected utility, mean-variance, Kelly, market efficiency.",
     "مطلوبیت انتظاری، میانگین–واریانس، کِلی، کارایی بازار.",
     "core/portfolio.kelly_multi · allocator"),
    ("Artificial Intelligence in Finance", "Yves Hilpisch", "PY",
     "ML/DL for prediction, its limits (efficiency), proper evaluation, vectorised RL ideas.",
     "ML/DL برای پیش‌بینی، محدودیت‌ها، ارزیابی درست، ایده‌های RL.",
     "ML Lab · regime_ensemble (transparent policy)"),
    # ---- Phase 16: low-timeframe / order-flow research pass
    ("Trading Price Action Trends / Reversals / Ranges", "Al Brooks", "TA",
     "Every bar is a signal bar or a setup; H1/H2 & L1/L2 two-legged pullbacks in an EMA-20 trend; always-in direction; measured moves; most breakouts fail — trade the second entry.",
     "هر کندل یا سیگنال است یا ستاپ؛ پولبک دوپایه‌ای H1/H2 و L1/L2 در روند EMA20؛ جهت «همیشه‌در»؛ حرکت اندازه‌گیری‌شده؛ بیشتر شکست‌ها شکست می‌خورند — ورود دوم را معامله کن.",
     "strategy brooks_h2l2 · Fast Signals radar"),
    ("Understanding Price Action", "Bob Volman", "TA",
     "5-minute EUR/USD scalping: double-pressure, pullback reversal, pattern break with 20-EMA, tight bracket 10/20 pips — the 'squeeze then pop' logic and the discipline of skipping mid-range.",
     "اسکالپ ۵ دقیقه‌ای: فشار دوطرفه، برگشت پولبک، شکست الگو با EMA20، براکت تنگ — منطق «فشردگی سپس پاپ» و انضباط ردکردن وسط رنج.",
     "strategy micro_squeeze_pop · vwap_pullback_scalp"),
    ("Street Smarts", "Linda Raschke & Laurence Connors", "TA",
     "Turtle Soup (failed 20-day breakout), 80-20s, Holy Grail, Anti — short-term patterns with explicit stops and time exits.",
     "ترتل سوپ (شکست ۲۰ روزهٔ ناموفق)، 80-20، هولی گریل، آنتی — الگوهای کوتاه‌مدت با حد ضرر و خروج زمانی صریح.",
     "strategy stop_run_scalp (intraday Turtle Soup) · holy_grail · anti"),
    ("Mind over Markets", "James Dalton", "TA",
     "Market Profile: Initial Balance, range extension, day types (normal / trend / neutral), value area, responsive vs initiative activity.",
     "مارکت پروفایل: تعادل اولیه، گسترش رنج، انواع روز، ناحیهٔ ارزش، فعالیت واکنشی در برابر ابتکاری.",
     "strategy ib_extension · session_orb"),
    ("Day Trading with Short Term Price Patterns and Opening Range Breakout", "Toby Crabel", "TA",
     "ORB, NR4/NR7, inside-day + NR — contraction predicts expansion; statistical tables per pattern.",
     "ORB، NR4/NR7، روز داخلی + NR — انقباض، انبساط را پیش‌بینی می‌کند؛ جدول‌های آماری هر الگو.",
     "strategy orb · nr7 · session_orb"),
    ("A Complete Guide to Volume Price Analysis", "Anna Coulling", "TA",
     "Volume validates price: climax bars, stopping volume, no-demand/no-supply, effort vs result on every timeframe.",
     "حجم قیمت را تأیید می‌کند: کندل کلایمکس، حجم توقف، بی‌تقاضا/بی‌عرضه، تلاش در برابر نتیجه.",
     "strategy volume_climax_scalp · cvd_divergence (BVC delta proxy)"),
    ("Flow Toxicity and Liquidity in a High-Frequency World (VPIN / Bulk Volume Classification)", "Easley, López de Prado, O'Hara", "Quant",
     "Classify volume as buy/sell from bar geometry (BVC) when tick data is unavailable → order-flow imbalance & CVD proxy.",
     "طبقه‌بندی حجم به خرید/فروش از هندسهٔ کندل (BVC) وقتی دیتای تیک نیست → عدم‌تعادل جریان سفارش و پراکسی CVD.",
     "core/strategies/scalp._cvd · cvd_divergence · funding_crowd_reversal"),
    ("Perpetual-swap positioning research (funding rate, open interest, liquidation clusters, CVD × funding confluence)", "Crypto derivatives desks, 2023–2026 write-ups", "Quant",
     "Elevated funding + price high not confirmed by CVD = squeeze fuel on the wrong side; negative funding at lows + bullish CVD divergence = Wyckoff spring with quantitative confirmation.",
     "فاندینگ بالا + سقفی که CVD تأیید نمی‌کند = سوخت اسکوئیز سمت اشتباه؛ فاندینگ منفی روی کف + واگرایی صعودی CVD = اسپرینگ وایکاف با تأیید کمّی.",
     "core/derivs (OKX/Binance funding & OI) · strategy funding_crowd_reversal · Fast Signals positioning column"),
    ("Independent 1-minute scalping backtests 2026 (Stratbase, Upscale, TradeZella, ChartingLens)", "various", "Quant",
     "After realistic fees only VWAP-anchored and limit-order setups stayed positive (PF 1.14–1.31); EMA 9/21 micro-cross PF 0.94; London/NY-overlap filter PF 1.14 → 1.32; RSI-7 replaces RSI-14 on 1m.",
     "بعد از کارمزد واقعی فقط ستاپ‌های لنگر VWAP و سفارش لیمیت مثبت ماندند (PF ۱.۱۴–۱.۳۱)؛ کراس EMA 9/21 PF ۰.۹۴؛ فیلتر هم‌پوشانی لندن/نیویورک PF ۱.۱۴ → ۱.۳۲؛ RSI-7 جای RSI-14 روی ۱ دقیقه.",
     "strategies vwap_pullback_scalp · vwap_band_fade · triple_confirm_scalp · fast_rsi_div_scalp · Fast Signals cost gate"),
    ("Footprint / order-flow field guides 2025–26 (imbalance 3:1, stacked imbalances, absorption, unfinished auctions, P/b profiles)", "FuturesHive · GoCharting · AlgoStorm · Bookmap edu", "Order flow",
     "Diagonal bid/ask imbalance ≥ 3:1; 3+ stacked = S/R zone worth a retest; absorption = huge volume, no progress; poor high/low = magnet; setups only at VAH/VAL/POC/LVN; stop a few ticks past the signal bar, ≥ 1.5R, half off at 1R.",
     "عدم‌تعادل قطری ≥ ۳:۱؛ ۳ سطح پشت‌سرهم = ناحیهٔ S/R قابل ری‌تست؛ جذب = حجم عظیم بدون پیشروی؛ سقف/کف ضعیف = آهن‌ربا؛ ستاپ فقط در VAH/VAL/POC/LVN؛ استاپ چند تیک پشت کندل سیگنال، ≥ ۱.۵R، نصف در ۱R.",
     "strategies stacked_imbalance_retest · unfinished_auction · value_area_bounce · lvn_breakout · rolling_profile helper (OHLCV proxies — no tick data)"),
    ("Fabio Valentini NQ playbook (balance vs imbalance day, CVD direction, location, aggression, Triple-A)", "F. Valentini (via PickMyTrade write-up)", "Order flow",
     "One market, one session; classify the day; direction from CVD; enter only where location + aggression agree; Triple-A = absorption → accumulation → aggressive expansion; max 3 losses/day.",
     "یک بازار، یک سشن؛ نوع روز را مشخص کن؛ جهت از CVD؛ فقط جایی که مکان + تهاجم هم‌جهت‌اند وارد شو؛ Triple-A = جذب → انباشت → انبساط تهاجمی؛ حداکثر ۳ باخت در روز.",
     "strategies triple_a_flow · anchored_scalp · Fast Signals session/cost gate · Risk desk daily-loss stop"),
    ("NostalgiaForInfinity (NFI X) — structure analysis", "iterativ & community (freqtrade)", "Bot",
     "5m base; ROI 100 / stoploss −0.99 (exits only by signal); ~65 buy-condition combos of ~26 shared params (EWO up/down, BB dip, RSI, informative 1h/4h/1d gates); huge drawdown without protections; winrate can be low with long holds.",
     "پایهٔ ۵ دقیقه؛ ROI ۱۰۰ / استاپ −۰.۹۹ (خروج فقط با سیگنال)؛ ~۶۵ ترکیب شرط خرید از ~۲۶ پارامتر مشترک (EWO، دیپ BB، RSI، گیت‌های ۱h/۴h/۱d)؛ بدون protections دراودان بزرگ.",
     "strategies nfi_dip_multi · nfi_lite · Bot desk protections"),
    ("freqtrade community 'Scalp' strategy autopsy (EMA5 hi/lo, STOCHF<30, ADX>30, BB lower; ROI 1 %, SL −4 %)", "freqst.com backtest", "Bot",
     "113 trades/day → −43 % after fees: a 1 % target with 4 % stop and taker fees is structurally negative; only usable with a trend gate, wider ATR stop and maker fees.",
     "۱۱۳ معامله در روز → −۴۳٪ بعد از کارمزد: هدف ۱٪ با استاپ ۴٪ و کارمزد تیکر ساختاراً منفی است؛ فقط با گیت روند، استاپ ATR پهن‌تر و کارمزد میکر قابل استفاده است.",
     "strategy ft_scalp (re-risked) · Fast Signals cost gate · Scalp WFO"),
    ("Flat-Bollinger + Stochastic quiet-hours scalp (r/Forex, r/Daytrading 2025)", "retail community", "Scalping",
     "Only when the bands are flat (band-width in the bottom quintile) and the session is quiet: fade band touches with Stoch OS/OB, target the opposite band, stop = distance to the middle band; avoid overtrading.",
     "فقط وقتی باندها صاف‌اند (پهنای باند در پایین‌ترین پنجک) و سشن آرام است: لمس باند با استوکاستیک اشباع را فید کن، هدف باند مقابل، استاپ = فاصله تا باند میانی؛ از اورتریدینگ بپرهیز.",
     "strategy flat_bb_stoch · Fast Signals session factor"),
    ("Walk-forward analysis (Pardo; Davey 'Building Winning Algorithmic Trading Systems')", "R. Pardo · K. Davey", "Quant",
     "Optimise on rolling in-sample, test on the next out-of-sample; Walk-Forward Efficiency = OOS/IS performance; only trade what survives OOS.",
     "روی پنجرهٔ درون‌نمونه بهینه کن، روی پنجرهٔ بعدی برون‌نمونه بیازما؛ کارایی WF = عملکرد OOS/IS؛ فقط چیزی را معامله کن که از OOS جان سالم به در برد.",
     "core/scalp_wfo (confluence-knob walk-forward per symbol) · Fast Signals ▸ WFO button"),
]
BOTS = [
    ("NostalgiaForInfinity X (freqtrade)", "all-round", "5m; 65 buy combos; EWO regime split; informative 1h/4h gates; exits by signal only", "nfi_dip_multi · nfi_lite · Bot desk protections"),
    ("OrderFlow / Bookmap / ATAS-style footprint bots", "order flow", "Imbalance, stacked imbalance, absorption, delta divergence, value-area location", "stacked_imbalance_retest · triple_a_flow · value_area_bounce · lvn_breakout · unfinished_auction (OHLCV proxies)"),
    ("Freqtrade", "all-round", "Strategy interface, hyperopt, protections, FreqAI", "freqtrade_sample · protections (StoplossGuard/MaxDrawdown/Cooldown/LowProfit) · pairlist filters (Bot desk) · ft_ema800 · ft_double_ema · ft_rsi_dir · binhv45 · clucmay · bband_rsi_bot · adx_momentum_bot · macd_cci_bot · nfi_lite · nfi_dip_multi (NFI EWO+BB-dip+informative gate) · ft_scalp (community Scalp, re-risked)"),
    ("Jesse", "all-round", "Clean strategy class, risk-based sizing, anchor timeframe (trade TF × 12 for bias, entry on trade TF)", "jesse_trend_atr · jesse_anchor (anchor TF) · anchored_scalp (Jesse anchor idea applied to 5m/15m with VWAP + CVD)"),
    ("OctoBot", "all-round", "Evaluator voting in [-1,1], daily trading mode", "octobot_daily · Quant Lab ▸ Bot desk (evaluator matrix)"),
    ("Superalgos", "all-round", "LRC + Bollinger channel/sub-channel strategies", "superalgos_lrc"),
    ("Hummingbot", "arbitrage/MM", "Pure & Avellaneda–Stoikov market making (reservation price, spread)", "Quant Lab ▸ Bot desk (A-S reservation price & optimal spread) · hummingbot_fv (as fair-value reversion signal)"),
    ("Blackbird / ArbitrageBot", "arbitrage", "Spread arbitrage between venues → spread z-score", "Quant Lab ▸ Bot desk (Blackbird spread_entry/exit) · Pairs (cointegration spread) · chan_statarb"),
    ("Gekko", "light", "MACD & DEMA with persistence thresholds", "gekko_macd · gekko_dema"),
    ("Zenbot", "light", "trend_ema default (rate + neutral zone), RSI dip", "zenbot_trend_ema"),
    ("Binance-trading-bot (chrisleekr)", "light", "Buy dips, sell grid, trailing thresholds", "grid_bot · dca_bot"),
    ("MagiBot", "light", "DCA + indicator gate", "dca_bot"),
    ("TensorTrade", "AI", "RL agent: state → action; reward shaping", "regime_ensemble (transparent policy) · ML Lab"),
    ("Freqtrade + TensorFlow (FreqAI)", "AI", "Feature engineering + model per pair, retrain on schedule", "core/ml.py (triple barrier, purged WF, meta-label) · maintenance retrain"),
    ("3Commas", "semi-open", "DCA bot with safety orders, take-profit from average", "dca_bot"),
    ("Bitsgap", "semi-open", "Grid bot, range-bound profit", "grid_bot"),
    ("Pionex", "semi-open", "Grid / infinity grid / DCA", "grid_bot · dca_bot"),
    # ---- Phase 11: AI libraries (what was learned from each and where it lives)
    ("TensorTrade", "AI/RL", "Env = exchange + action scheme + reward scheme + observer; separation of concerns", "core/rl.TradingEnv (window observer, cost model, logret/DSR reward) · AI Desk ▸ RL"),
    ("LEAN / QuantConnect", "engine", "Algorithm Framework: Alpha→Portfolio→Risk→Execution; consolidators; reality models", "core/engines.AlgorithmFramework · consolidate() · AI Desk ▸ Engines"),
    ("Zipline", "engine", "Pipeline cross-sectional factors; VolumeShare/FixedBps slippage; PerShare commission", "core/engines.pipeline_rank · volume_share_slippage · AI Desk ▸ Engines"),
    ("Backtrader (+AI)", "engine", "next()-loop event engine, bracket orders, sizers, SQN analyzer, next-bar fills", "core/engines.EventEngine · SignalStrategy adapter · parity_check vs vectorised backtester"),
    ("Prophet / NeuralProphet", "AI/forecast", "Piecewise-linear trend with changepoints + seasonality + uncertainty band; changepoint prior", "core/forecast.prophet_like (damped, anchored) · AI Desk ▸ Forecast band"),
    ("Kats", "AI/forecast", "CUSUM changepoint detection, ensemble backtesting", "core/forecast.cusum_changepoints · historical_forecasts"),
    ("Darts / sktime", "AI/forecast", "Unified fit/predict API, historical_forecasts (rolling origin), Theta, MASE metric", "core/forecast.MODELS · historical_forecasts (MASE, direction p-value)"),
    ("PyTorch Forecasting / GluonTS", "AI/forecast", "N-BEATS basis expansion; probabilistic (quantile) forecasts", "core/forecast.nbeats_like (mlp/ridge) · quantile_forecast (pinball loss)"),
    ("FinBERT / finance BERT", "AI/NLP", "3-class finance sentiment; optional transformer backend", "core/sentiment.transformer_backend (auto if transformers installed) · FinBERT column"),
    ("VADER / TextBlob / Flair / Stanza", "AI/NLP", "Rule lexicon with negation/boosters/caps, subjectivity, entity (ticker) extraction", "core/sentiment.vader_like · subjectivity · per_ticker · Loughran-McDonald lexicon · crowd flag"),
    ("FinGPT / fin-tuned Llama·Mistral·DeepSeek·Qwen·Falcon", "AI/LLM", "Grounded report writing & instruction Q&A over market context; local inference", "core/analyst.report/ask (offline rule-writer) · local GGUF via llama-cpp in data/models · AI Desk ▸ Analyst · Vision ▸ Ask"),
    ("Stable-Baselines3 / RLlib / Coach", "AI/RL", "Gym env contract, PPO/DQN, EvalCallback early stopping, multi-seed evaluation", "core/rl.LinearQAgent/LinearPolicyAgent · train_and_evaluate (val early-stop, random-p95 baseline) · sb3_backend"),
    ("YOLO / Detectron2 / OpenCV+PyTorch", "AI/vision", "Detector = proposals → class scores → NMS; train on labelled (synthetic) data; multi-scale", "core/vision (OpenCV candle segmentation, OCR axis calibration, Hough drawings, volume pane) · core/vision2.PatternDetector (HOG+SVM sliding-window + NMS) · Chart Vision page"),
]

